[theme]
base = "dark"
primaryColor = "#cb9e21"
backgroundColor = "#0D100B"
secondaryBackgroundColor = "#1A2016"
textColor = "#EAEAEA"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false
