[theme]
base = "dark"
primaryColor = "#C2694F"
backgroundColor = "#302B27"
secondaryBackgroundColor = "#3B3540"
textColor = "#E8DDD4"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false
